### ISSUE TITLE
Desktop View Regression Tests

### ISSUE THREAD

**Issue by kavinphan** [GTBitsOfGood/the-ray#123]
### Description
Because of the changes of nearly every page for the mobile view effort, some screens may have experienced regressions  in quality for the desktop view.

Verify that every screen in the desktop view matches what is shown in the Figma.

### Acceptance Criteria
- [ ] The desktop screens match the Figma : )

### Other Notes
* [Figma](https://www.figma.com/file/5nnP85rbDofwvwtpNdNHeC/The-Ray)

**Comment by its-edmund** [comment]
@izou3 reported that the desktop views are fine
