### ISSUE TITLE
PV4EV 23710/CO2 Mobile View

### ISSUE THREAD

**Issue by kavinphan** [GTBitsOfGood/the-ray#93]
### Description
On the PV4EV page, the 23710/CO2 sections need to have their mobile design implemented.

### Acceptance Criteria
[ ] On the PV4EV page, the 23710/CO2 sections will match their design on the Figma page for the **DESKTOP** view
[ ] On the PV4EV page, the 23710/CO2 sections will match their design on the Figma page for the **MOBILE** view

### Other Notes
[Figma](https://www.figma.com/file/5nnP85rbDofwvwtpNdNHeC/The-Ray?node-id=2217%3A2)

**Comment by Fattimo** [comment]
what px is the breakpoint for mobile?
